setting up the APF-authorized system link list dataset

diff --git a/bin/llregistrar b/bin/llregistrar
--- a/bin/llregistrar
+++ b/bin/llregistrar
@@ -31,18 +31,18 @@ msg() {
 #
 syntax() {
 	echo "\
-apfregistrar [-vd] <swname> enable|disable [dataset]+
+llregistrar [-vd] <swname> enable|disable [dataset]+
 
 Examples:
-	Enable APF authorization for dataset ZBREW.EQAE20.SEQAAUTH
-		apfregistrar eqae20 enable zbrew.eqae20.seqaauth
-	Disable APF authorization for EQAE20 datasets
-        	apfregistrar eqae20 disable 5737-I22
+	Enable linklist entry for dataset ZBREW.EQAE20.SEQABMOD
+		llregistrar eqae20 enable zbrew.eqae20.seqabmod
+	Disable linklist entry for EQAE20 datasets
+        	llregistrar eqae20 disable
 Note:
 	The PDS \${ZBREW_ROOT}PARMLIB is created if it does not already exist
 	The PDS member PROG\${ZBREW_PARMLIB_SFX} is created if it does not already exist
-	The PDS member will have the new APF authorized datasets added if 'enable' is specified
-	The PDS member will have the APF authorized datasets removed if 'disable' is specified.
+	The PDS member will have the new link list datasets added if 'enable' is specified
+	The PDS member will have the link list datasets removed if 'disable' is specified.
 	Enabling a product that already has an entry is an error.
 	Disabling a product that does not have an entry is silent.
 	Disabling a product removes the entry from the file - it does NOT mark as DISABLED
@@ -63,7 +63,7 @@ while getopts ":vdf" opt; do
       ;;
     \?)         
       if [ ${OPTARG} != "?" ]; then
-        msg apfregistrar ${InvalidOption} E "${OPTARG}"
+        msg llregistrar ${InvalidOption} E "${OPTARG}"
       fi                
       syntax
       exit 4
@@ -72,7 +72,7 @@ while getopts ":vdf" opt; do
 done    	
 shift $(expr $OPTIND - 1 )
 if [ $# -lt 3 ]; then
-        msg apfregistrar ${TooFewParms} E "$#"
+        msg llregistrar ${TooFewParms} E "$#"
  	syntax
         exit 8
 fi  
@@ -90,36 +90,39 @@ footer="/* --- ${sw} end   --- */"
 parmlibds="${ZBREW_TGT_HLQ}PARMLIB"
 member="PROG${ZBREW_PARMLIB_SFX}"
 
+llname=`opercmd 'd lla' 2>/dev/null | grep 'LNKLST SET' | awk ' { print $3; }'`
+datasets=$(echo $datasets | tr '[:lower:]' '[:upper:]');
+for dataset in ${datasets}; do
+        info=`dls -l ${dataset}`
+        if [ $? -gt 0 ]; then
+        	echo "llregistrar: Dataset: ${dataset} not found." >&2
+       		exit 16
+        fi
+done 
+
 if [ "${verb}" = "DISABLE" ]; then
 	registrar "${sw}" "DISABLE" "${parmlibds}" "${member}" "${header}" "${footer}"
+	for dataset in ${datasets}; do
+		opercmd "SETPROG LNKLST,DELETE,NAME=${llname},DSNAME=${dataset}"
+	done
+	opercmd "MODIFY LLA,REFRESH"
 	exit $?
 fi
 
-for dataset in ${datasets}; do
-	dataset=$(echo $dataset | tr '[:lower:]' '[:upper:]');
-	info=`dls -l ${dataset}`
-	if [ $? -gt 0 ]; then
-		echo "apfregistrar: Dataset: ${dataset} not found." >&2
-		exit 16
-	fi
-	volume=`echo "${info}" | awk '{ print $5; }'`
-	opercmd "d sms,volume(${volume})" 2>/dev/null | grep "NOT AN SMS MANAGED DASD VOLUME"
-	if [ $? -gt 0 ]; then
-		volume="SMS"
-		setstr="SMS"
-	else
-		setstr="VOLUME=${volume}"
-	fi
+# ENABLE follows
 
-	entry="APF ADD DSNAME(${dataset}) ${volume}"
+for dataset in ${datasets}; do
+	entry="LNKLST ADD NAME(${llname}) DSNAME(${dataset})"
 	if [ "${text}" = "" ]; then
 		text="${entry}"
 	else
 		text="${entry}
 ${text}"
 	fi
-	opercmd "SETPROG APF,ADD,DSNAME=${dataset},${setstr}"
+	# msf - this is not sufficient - the entry is not getting added
+	opercmd "SETPROG LNKLST,ADD,NAME=${llname},DSNAME=${dataset}"
 done
+opercmd "MODIFY LLA,REFRESH"
 
 registrar "${sw}" "${verb}" "${parmlibds}" "${member}" "${header}" "${footer}" "${text}"
 exit $?
