prevent using -c when $sw has parent

diff --git a/bin/prodclean b/bin/prodclean
--- a/bin/prodclean
+++ b/bin/prodclean
@@ -78,6 +78,12 @@ smpelibs="${mydir}/../../zbrew-${prefix}/${ussname}/${ussname}bom.json"
 ussname=$(echo ${ussname} | tr '[:lower:]' '[:upper:]')
 
 swparent=`readbom ${ussname} summary <${smpelibs}`
+rc=$?
+if [ $rc -gt 0 ]; then
+	echo "$swparent"
+	exit $rc
+fi
+
 if [ "$swparent" != "0" ]; then
 	echo "Warning: Product $zosname is installed into the SMP/E zone for $swparent" >&2 
 	echo "Only $zosname specific cleanup will be performed" >&2 
@@ -98,7 +104,7 @@ unm=`echo "${libs}" | awk -v zbr="$ZBREW_ZFSROOT" '($2 == "ZFS") {system("/usr/s
 out=`drm -f "${ZBREW_HLQ}${zosname}*.**"`
 rc=$?
 if [ $rc -gt 0 ]; then
-        echo "Dataset cleanup failed. UnInstall aborted"
+        echo "Dataset cleanup failed. UnInstall aborted" >&2
         exit $rc
 fi
 
diff --git a/bin/zbrew b/bin/zbrew
--- a/bin/zbrew
+++ b/bin/zbrew
@@ -339,17 +339,39 @@ zosname=$(echo ${sw} | tr '[:lower:]' '[:upper:]');
 zosfile=$(echo ${3} | tr '[:lower:]' '[:upper:]');
 
 if [ "${clean}" = "1" ]; then
-                out=`prodclean ${opts} ${sw}`
-                rc=$?
-                zbrewlog "Cleanup for ${sw} Return Code: ${rc}"
-                if [ "${verbose}" = "1" ]; then
-                        echo "Cleanup completed: ${rc}"
-                fi
-                if [ $rc -gt 0 ]; then
-			"Cleanup failed with Return code: ${rc}"
-                        echo "${out}"
-			exit ${rc}
-                fi
+	prefix=`echo "${ussname}" | awk '{ print substr($1, 0, 3) }'`
+	bomfile="${mydir}/../../zbrew-${prefix}/${ussname}/${ussname}bom.json"
+	swparent=`readbom ${ussname} summary <${bomfile}`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+        	echo "$swparent"
+        	exit $rc
+	fi
+
+	if [ "$swparent" != "0" ]; then
+        	echo "Warning: Product $zosname is installed into the SMP/E zone for $swparent" >&2
+        	echo "Using the -c option is invalid under these conditions" >&2
+        	echo " " >&2
+        	echo "If you need to install $zosname, then remove the -c option" >&2
+        	echo " " >&2
+        	echo "If you need to RE-install $zosname, then manual actions may be required for $swparent" >&2
+        	echo "to clean up SMP/E or alternatively you will need to first uninstall and reinstall $swparent" >&2
+        	echo " " >&2
+        	echo "If you really wish to uninstal $zosname then run zbrew uninstall $zosname" >&2
+		exit 16
+	fi
+
+	out=`prodclean ${opts} ${sw}`
+	rc=$?
+	zbrewlog "Cleanup for ${sw} Return Code: ${rc}"
+	if [ "${verbose}" = "1" ]; then
+		echo "Cleanup completed: ${rc}"
+	fi
+	if [ $rc -gt 0 ]; then
+		"Cleanup failed with Return code: ${rc}"
+		echo "${out}"
+		exit ${rc}
+	fi
 
 fi
 verb=$1
