support multiple child relationships

diff --git a/bin/prodclean b/bin/prodclean
--- a/bin/prodclean
+++ b/bin/prodclean
@@ -93,34 +93,41 @@ fi
 
 if [ "$swparent" != "0" ]; then
 	echo " " >&2
-	echo "*************************************************************************** " >&2
+	echo "***************************************************************************** " >&2
 	echo " " >&2
-	echo "Warning: Product $zosname is installed into the SMP/E zone for $swparent" >&2 
+	echo "Warning: Product $zosname is installed into the same SMP/E zone for $swparent" >&2 
 	echo "Only $zosname specific cleanup will be performed" >&2 
 	echo "If you need to re-install $zosname, then you MUST Either take manual action " >&2 
 	echo "to clean up SMP/E or alternatively uninstall and reinstall $swparent" >&2 
-	echo "*************************************************************************** " >&2
+	echo "***************************************************************************** " >&2
 fi
 
-if [ "$swchild" != "0" ]; then
+if [ "$swchild" != "0" ] && [ "$swchild" != "" ]; then
 	echo " " >&2
-	echo "************************************************************************************************************* " >&2
-        echo "Warning: Product $zosname is a parent to $swchild. $swchild is installed in the same SMP/E zone as $zosname" >&2
-        echo "By running uninstall or using the -c option for $zosname, means the SMP/E environment for $swchild is affected." >&2
-        echo "Zbrew will automatically uninstall $swchild as a result." >&2
-        echo "If desired you will need to reinstall $swchild after re-installing $zosname." >&2
-	echo "************************************************************************************************************* " >&2
+	echo "*************************************************************************************************************** " >&2
+        echo "Warning: Product $zosname is in a child/parent relationshiop and has other products installed in it's SMP/E zone" >&2
+        echo "By running uninstall or using the -c option for $zosname, means the below listed products are also affected." >&2
+        echo "Zbrew will automatically uninstall all the below listed products as a result." >&2
+        echo "If desired you will need to reinstall these products after re-installing $zosname." >&2
+	echo "**************************************************************************************************************** " >&2
+	echo "The following Product(s) are affected: ">&2
+        for ch in ${swchild}; do
+		echo "*** ${ch} ***" >&2
+	done
+        for ch in ${swchild}; do
+		if [ "${verbose}" = "1" ]; then
+	                echo "Proceeding to uninstall $ch" >&2
+        	fi
+		uninst=`zbrew uninstall ${ch}`
+	        if [ "${rc}" != 0 ]; then
+	                echo "Uninstall of ${ch} failed." >&2
+        	        echo "${uninst}" >&2
+              		exit 16
+       		fi
+
+        done
 	echo " "
-	if [ "${verbose}" = "1" ]; then
-		echo "Proceeding to uninstall $swchild" >&2
-	fi
-	uninst=`zbrew uninstall ${swchild}`
 	rc=$?
-	if [ "${rc}" != 0 ]; then
-		echo "Uninstall of ${swchild} failed." >&2
-		echo "${uninst}" >&2
-		exit 16
-	fi
 fi
 
 libs=`readbom ${ussname} <${smpelibs}`
