refactored code to use a new utility - smp - for issuing SMP commands

diff --git a/bin/smpchkptf b/bin/smpchkptf
--- a/bin/smpchkptf
+++ b/bin/smpchkptf
@@ -52,54 +52,36 @@ runchk() {
 	echo "  SET BOUNDARY(GLOBAL).
   LIST GZONE.
 " >${tmpCntlHFS}
-	
-	LOG=${TMP}/$$.smplog
-	touch ${LOG}
+	gzonelist=${TMP}/$$.smp.gzonelst
 
-	OUT=${TMP}/$$.smpout
-	touch ${OUT}
-
-	RPT=${TMP}/$$.smprpt
-	touch ${RPT}
-
-	LIST=${TMP}/$$.smplist
-        touch ${LIST}
-
-        SYSPRINT=${TMP}/$$.sysprint
-        touch ${SYSPRINT}   	
-
-        mvscmdauth --pgm=gimsmp --smpcsi=${csi} --smplog=${LOG},mod --smpout=${OUT},mod --smprpt=${RPT},mod --sysprint=${SYSPRINT},mod --smplist=${LIST},mod --smpcntl=${tmpCntlHFS}
+	smpout=`smp -i ${csi} -l ${gzonelist} <${tmpCntlHFS}`	
 	rc=$?
  	if [ ${rc} -gt 0 ]; then
-                echo "Unable to determine global zone for: ${csi}. See SYSPRINT: ${SYSPRINT}, SMPLOG: ${LOG}, SMPOUT: ${OUT}, SMPRPT: ${RPT}, SMPCNTL:${tmpCntlHFS} for details."
+                echo "Unable to determine global zone for: ${csi}." >&2
+		echo "${smpout}" >&2
 		return ${rc}
- 	else
-         	rm -rf ${LOG} ${OUT} ${RPT} ${SYSPRINT} ${tmpCntlHFS}
        	fi
-	tgtzones=`cat ${LIST} | awk '{ if ($2=="TARGET" && NF==3) { print($1); } }'`
-	rm ${LIST}
+	tgtzones=`awk '{ if ($2=="TARGET" && NF==3) { print($1); } }' -f ${gzonelist}`
+        rm ${tmpCntlHFS}
 	if [ "${tgtzones}" = '' ]; then
-		echo "Internal error. Unable to	determine global zone for: ${csi}. See SYSPRINT: ${SYSPRINT}, SMPLOG: ${LOG}, SMPOUT: ${OUT}, SMPRPT: ${RPT}, SMPCNTL:${tmpCntlHFS} for	details."
+		echo "Internal error. Unable to	determine global zone for: ${csi}. See ${gzonelist} for details." >&2
 		return 16
 	fi
+	ptflist=${TMP}/$$.smp.ptflst
 	for tgtzone in $tgtzones; do
 		if [ ${verbose} -gt 0 ]; then
 			echo "Checking target zone: ${tgtzone}" >&2
 		fi
-		touch ${LOG} ${OUT} ${RPT} ${LIST} ${SYSPRINT}
-		tmpCntlHFS=${TMP}/$$.cntl.xml
 		echo "  SET BOUNDARY(${tgtzone}).
   LIST PTFS.
 " >${tmpCntlHFS}
-		mvscmdauth --pgm=gimsmp --smpcsi=${csi} --smplog=${LOG},mod --smpout=${OUT},mod --smprpt=${RPT},mod --sysprint=${SYSPRINT},mod --smplist=${LIST},mod --smpcntl=${tmpCntlHFS}
+		smpout=`smp -c ${csi} -l ${ptflist} <${tmpCntlHFS}`
 		rc=$?
 		if [ ${rc} -gt 0 ]; then
 			echo "Warning: Unable to determine PTF list for target zone ${tgtzone}." >&2
 		else
-        	   	rm -rf ${LOG} ${OUT} ${RPT} ${SYSPRINT} ${tmpCntlHFS}
-
-			allptfs=`cat ${LIST} | awk '{ if ($2=="TYPE" && $3=="=" && $4=="PTF" && NF==4) { print($1); } }'`
-			rm ${LIST}
+			allptfs=`awk '{ if ($2=="TYPE" && $3=="=" && $4=="PTF" && NF==4) { print($1); } }' -f ${ptflist}`
+			rm ${ptflist}
 			if [ "${allptfs}" = '' ]; then
 				if [ ${verbose} -gt 0 ]; then
 					echo "No PTFs in target zone: ${tgtzone}" >&2
diff --git a/bin/smpreceive b/bin/smpreceive
--- a/bin/smpreceive
+++ b/bin/smpreceive
@@ -79,21 +79,6 @@ zzz
       .
 zzz
 
-	LOG=${TMP}/$$.smplog
-	touch ${LOG}
-
-	OUT=${TMP}/$$.smpout
-	touch ${OUT}
-
-	RPT=${TMP}/$$.smprpt
-	touch ${RPT}
-
-	BPXPRINT=${TMP}/$$.bpxprint
-	touch ${BPXPRINT}
-
-	SYSPRINT=${TMP}/$$.sysprint
-	touch ${SYSPRINT}
-
 	NTS=${TMP}/smpnts
 
 	if [ ${clean} -gt 0 ]; then
@@ -101,13 +86,13 @@ zzz
 	fi
 	mkdir -p ${NTS}
 
-	mvscmdauth --pgm=gimsmp --smpcsi=${ZBREW_HLQ}${sw}G.GLOBAL.CSI --smpwkdir=${TMP} --smpnts=${NTS} --smplog=${LOG},mod --smpout=${OUT},mod --smprpt=${RPT},mod --bpxprint=${BPXPRINT},mod --sysprint=${SYSPRINT},mod --server=${tmpServerHFS} --client=${tmpClientHFS} --smpcntl=${tmpCntlHFS}
+	smpout=`smp -i ${ZBREW_HLQ}${sw}G.GLOBAL.CSI -w ${TMP} -n ${NTS} -c ${tmpClientHFS} -s ${tmpServerHFS} <${tmpCntlHFS}`
 	rc=$?
 	if [ ${rc} -gt 0 ]; then
-		echo "SMP/E RECEIVE of ${sw} failed. See SYSPRINT: ${SYSPRINT}, BPXPRINT: ${BPXPRINT}, SMPLOG: ${LOG}, SMPOUT: ${OUT}, SMPRPT: ${RPT} for details."
-		echo "SMP/E RECEIVE INPUT Files have been retained: server:${tmpServerHFS} client:${tmpClientHFS} smpcntl:${tmpCntlHFS}"
+		echo "SMP/E RECEIVE of ${sw} failed." >&2
+		echo "${smpout}" >&2
+		echo "SMP/E RECEIVE INPUT Files have been retained: server:${tmpServerHFS} client:${tmpClientHFS} smpcntl:${tmpCntlHFS}" >&2
 	else
-		rm -rf ${LOG} ${OUT} ${RPT} ${BPXPRINT} ${SYSPRINT}
 		if [ ${clean} -gt 0 ]; then
 			rm -rf ${NTS}
 		fi
