change code to use a HLQ to put things under

diff --git a/bin/smpconfig b/bin/smpconfig
--- a/bin/smpconfig
+++ b/bin/smpconfig
@@ -102,33 +102,34 @@ definecsidatasets() {
 
 definesmpcntl() {
      HLQ="$1"
+     PFX="$2"
 
      echo "
   SET BOUNDARY(GLOBAL).
   UCLIN.
-    ADD OPTIONS(${HLQ}G)
-          DSPREFIX(${HLQ}G.SMPTLIB)
+    ADD OPTIONS(${PFX}G)
+          DSPREFIX(${HLQ}${PFX}G.SMPTLIB)
           DSSPACE(${DSSPACE})
           MSGFILTER(YES)
           MSGWIDTH(80)
           RECZGRP(ALLZONES)
           RETRYDDN(ALL).
     ADD GLOBALZONE
-          OPTIONS(${HLQ}G)
+          OPTIONS(${PFX}G)
           SREL(Z038)
           ZONEINDEX(
-                    (${HLQ}T,${HLQ}T.TARGET.CSI,TARGET)
-                    (${HLQ}D,${HLQ}D.DLIB.CSI,DLIB)
+                    (${PFX}T,${HLQ}${PFX}T.TARGET.CSI,TARGET)
+                    (${PFX}D,${HLQ}${PFX}D.DLIB.CSI,DLIB)
                    ).
     ADD DDDEF(SMPDEBUG) SYSOUT(*).
     ADD DDDEF(SMPLIST)  SYSOUT(*).
     ADD DDDEF(SMPRPT)   SYSOUT(*).
     ADD DDDEF(SMPSNAP)  SYSOUT(*).
     ADD DDDEF(SYSPRINT) SYSOUT(*).
-    ADD DDDEF(SMPLOG)   DA(${HLQ}G.GLOBAL.SMPLOG) MOD.
-    ADD DDDEF(SMPLOGA)  DA(${HLQ}G.GLOBAL.SMPLOGA) MOD.
+    ADD DDDEF(SMPLOG)   DA(${HLQ}${PFX}G.GLOBAL.SMPLOG) MOD.
+    ADD DDDEF(SMPLOGA)  DA(${HLQ}${PFX}G.GLOBAL.SMPLOGA) MOD.
     ADD DDDEF(SMPOUT)   SYSOUT(*).
-    ADD DDDEF(SMPPTS)   DA(${HLQ}G.SMPPTS) SHR.
+    ADD DDDEF(SMPPTS)   DA(${HLQ}${PFX}G.SMPPTS) SHR.
     ADD DDDEF(SYSUT1)   UNIT(SYSALLDA) CYLINDERS SPACE(25,25).
     ADD DDDEF(SYSUT2)   UNIT(SYSALLDA) CYLINDERS SPACE(50,50).
     ADD DDDEF(SYSUT3)   UNIT(SYSALLDA) CYLINDERS SPACE(50,50).
@@ -144,25 +145,25 @@ definesmpcntl() {
     ADD DDDEF(SMPWRK6)  UNIT(SYSALLDA) CYLINDERS SPACE(150,500)
                         DIR(1000).
   ENDUCL.
-  SET BOUNDARY(${HLQ}T).
+  SET BOUNDARY(${PFX}T).
   UCLIN.
-    ADD TARGETZONE(${HLQ}T)
-          OPTIONS(${HLQ}G)
+    ADD TARGETZONE(${PFX}T)
+          OPTIONS(${PFX}G)
           SREL(Z038)
-          RELATED(${HLQ}D).
+          RELATED(${PFX}D).
     ADD DDDEF(SMPDEBUG) SYSOUT(*).
     ADD DDDEF(SMPLIST)  SYSOUT(*).
-    ADD DDDEF(SMPLOG)   DA(${HLQ}T.TARGET.SMPLOG) MOD.
-    ADD DDDEF(SMPLOGA)  DA(${HLQ}T.TARGET.SMPLOGA) MOD.
+    ADD DDDEF(SMPLOG)   DA(${HLQ}${PFX}T.TARGET.SMPLOG) MOD.
+    ADD DDDEF(SMPLOGA)  DA(${HLQ}${PFX}T.TARGET.SMPLOGA) MOD.
     ADD DDDEF(SMPOUT)   SYSOUT(*).
     ADD DDDEF(SMPRPT)   SYSOUT(*).
     ADD DDDEF(SMPSNAP)  SYSOUT(*).
     ADD DDDEF(SYSPRINT) SYSOUT(*).
-    ADD DDDEF(SMPPTS)   DA(${HLQ}G.SMPPTS) SHR.
-    ADD DDDEF(SMPSTS)   DA(${HLQ}T.TARGET.SMPSTS) OLD.
-    ADD DDDEF(SMPMTS)   DA(${HLQ}T.TARGET.SMPMTS) OLD.
-    ADD DDDEF(SMPLTS)   DA(${HLQ}T.TARGET.SMPLTS) OLD.
-    ADD DDDEF(SMPSCDS)  DA(${HLQ}T.TARGET.SMPSCDS) OLD.
+    ADD DDDEF(SMPPTS)   DA(${HLQ}${PFX}G.SMPPTS) SHR.
+    ADD DDDEF(SMPSTS)   DA(${HLQ}${PFX}T.TARGET.SMPSTS) OLD.
+    ADD DDDEF(SMPMTS)   DA(${HLQ}${PFX}T.TARGET.SMPMTS) OLD.
+    ADD DDDEF(SMPLTS)   DA(${HLQ}${PFX}T.TARGET.SMPLTS) OLD.
+    ADD DDDEF(SMPSCDS)  DA(${HLQ}${PFX}T.TARGET.SMPSCDS) OLD.
     ADD DDDEF(SYSLIB)   CONCAT(SMPMTS).
     ADD DDDEF(SYSUT1)   UNIT(SYSALLDA) CYLINDERS SPACE(250,250).
     ADD DDDEF(SYSUT2)   UNIT(SYSALLDA) CYLINDERS SPACE(50,50).
@@ -179,26 +180,26 @@ definesmpcntl() {
     ADD DDDEF(SMPWRK6)  UNIT(SYSALLDA) CYLINDERS SPACE(150,500)
                         DIR(1000).
   ENDUCL.
-  SET BOUNDARY(${HLQ}D).
+  SET BOUNDARY(${PFX}D).
   UCLIN.
-    ADD DLIBZONE(${HLQ}D)
-          OPTIONS(${HLQ}G)
+    ADD DLIBZONE(${PFX}D)
+          OPTIONS(${PFX}G)
           SREL(Z038)
           ACCJCLIN
-          RELATED(${HLQ}T).
+          RELATED(${PFX}T).
     ADD DDDEF(SMPDEBUG) SYSOUT(*).
     ADD DDDEF(SMPLIST)  SYSOUT(*).
-    ADD DDDEF(SMPLOG)   DA(${HLQ}D.DLIB.SMPLOG) MOD.
-    ADD DDDEF(SMPLOGA)  DA(${HLQ}D.DLIB.SMPLOGA) MOD.
+    ADD DDDEF(SMPLOG)   DA(${HLQ}${PFX}D.DLIB.SMPLOG) MOD.
+    ADD DDDEF(SMPLOGA)  DA(${HLQ}${PFX}D.DLIB.SMPLOGA) MOD.
     ADD DDDEF(SMPOUT)   SYSOUT(*).
     ADD DDDEF(SMPRPT)   SYSOUT(*).
     ADD DDDEF(SMPSNAP)  SYSOUT(*).
     ADD DDDEF(SYSPRINT) SYSOUT(*).
-    ADD DDDEF(SMPPTS)   DA(${HLQ}G.SMPPTS) SHR.
-    ADD DDDEF(SMPSTS)   DA(${HLQ}T.TARGET.SMPSTS) OLD.
-    ADD DDDEF(SMPMTS)   DA(${HLQ}T.TARGET.SMPMTS) OLD.
-    ADD DDDEF(SMPLTS)   DA(${HLQ}T.TARGET.SMPLTS) OLD.
-    ADD DDDEF(SMPSCDS)  DA(${HLQ}T.TARGET.SMPSCDS) OLD.
+    ADD DDDEF(SMPPTS)   DA(${HLQ}${PFX}G.SMPPTS) SHR.
+    ADD DDDEF(SMPSTS)   DA(${HLQ}${PFX}T.TARGET.SMPSTS) OLD.
+    ADD DDDEF(SMPMTS)   DA(${HLQ}${PFX}T.TARGET.SMPMTS) OLD.
+    ADD DDDEF(SMPLTS)   DA(${HLQ}${PFX}T.TARGET.SMPLTS) OLD.
+    ADD DDDEF(SMPSCDS)  DA(${HLQ}${PFX}T.TARGET.SMPSCDS) OLD.
     ADD DDDEF(SYSLIB)   CONCAT(SMPMTS).
     ADD DDDEF(SYSUT1)   UNIT(SYSALLDA) CYLINDERS SPACE(250,250).
     ADD DDDEF(SYSUT2)   UNIT(SYSALLDA) CYLINDERS SPACE(50,50).
@@ -228,8 +229,8 @@ configureCSI() {
 	# - DDDEF entries for operational and temporary data sets
 	#********************************************************************
 	#
-	smpcntl=`definesmpcntl "${HLQ}"`
-	mvscmdauth --pgm=GIMSMP --smpcsi=${GLOBAL_CSI} --smppts=${HLQ}G.SMPPTS --smplog='*' --smpout='*' --smprpt='*' --smplist='*' --sysprint='*' --smpcntl=stdin <<zzz
+	smpcntl=`definesmpcntl "${HLQ}" "${PFX}"`
+	mvscmdauth --pgm=GIMSMP --smpcsi=${GLOBAL_CSI} --smppts=${HLQ}${PFX}G.SMPPTS --smplog='*' --smpout='*' --smprpt='*' --smplist='*' --sysprint='*' --smpcntl=stdin <<zzz
 ${smpcntl}
 zzz
 	exit $?
@@ -287,15 +288,24 @@ if [ $# -lt 1 ]; then
 	exit 16
 fi      
 
-HLQ=$(echo ${1} | tr '[:lower:]' '[:upper:]');
+mydir=$(callerdir ${0})
+props="${mydir}/../properties/zbrew.properties"
+. zbrewprops "${props}"
+if [ $? -gt 0 ]; then
+        echo "Internal Error. Unable to find ${props}" >&2
+        exit 4
+fi   
 
-if [ ${#HLQ} -gt 6 ]; then
+PFX=$(echo ${1} | tr '[:lower:]' '[:upper:]');
+HLQ="${ZBREW_HLQ}"
+
+if [ ${#PFX} -gt 6 ]; then
 	msg smpconfig ${PrefixTooLong} E "${#HLQ}"
 	exit 16
 fi 
-GLOBAL_CSI="${HLQ}G.GLOBAL.CSI"
-TARGET_CSI="${HLQ}T.TARGET.CSI"
-DLIB_CSI="${HLQ}D.DLIB.CSI"
+GLOBAL_CSI="${HLQ}${PFX}G.GLOBAL.CSI"
+TARGET_CSI="${HLQ}${PFX}T.TARGET.CSI"
+DLIB_CSI="${HLQ}${PFX}D.DLIB.CSI"
 REPRO_FROM="SYS1.MACLIB(GIMZPOOL)"
 
 ## msf - need to move CSI allocation to be product specific for size reasons
@@ -308,17 +318,17 @@ if [ $rc -gt 0 ]; then
 	exit $rc
 fi
 
-datasets="${HLQ}G.SMPPTS:-s500M,-tpdse
-          ${HLQ}T.TARGET.SMPMTS:-tpds
-          ${HLQ}T.TARGET.SMPSTS:-tpds
-          ${HLQ}T.TARGET.SMPLTS:-tpds
-          ${HLQ}T.TARGET.SMPSCDS:-tpds
-          ${HLQ}G.GLOBAL.SMPLOG:-tseq,-rvb,-l150
-          ${HLQ}G.GLOBAL.SMPLOGA:-tseq,-rvb,-l150
-          ${HLQ}T.TARGET.SMPLOG:-tseq,-rvb,-l150
-          ${HLQ}T.TARGET.SMPLOGA:-tseq,-rvb,-l150
-          ${HLQ}D.DLIB.SMPLOG:-tseq,-rvb,-l150
-          ${HLQ}D.DLIB.SMPLOGA:-tseq,-rvb,-l150"
+datasets="${HLQ}${PFX}G.SMPPTS:-s500M,-tpdse
+          ${HLQ}${PFX}T.TARGET.SMPMTS:-tpds
+          ${HLQ}${PFX}T.TARGET.SMPSTS:-tpds
+          ${HLQ}${PFX}T.TARGET.SMPLTS:-tpds
+          ${HLQ}${PFX}T.TARGET.SMPSCDS:-tpds
+          ${HLQ}${PFX}G.GLOBAL.SMPLOG:-tseq,-rvb,-l150
+          ${HLQ}${PFX}G.GLOBAL.SMPLOGA:-tseq,-rvb,-l150
+          ${HLQ}${PFX}T.TARGET.SMPLOG:-tseq,-rvb,-l150
+          ${HLQ}${PFX}T.TARGET.SMPLOGA:-tseq,-rvb,-l150
+          ${HLQ}${PFX}D.DLIB.SMPLOG:-tseq,-rvb,-l150
+          ${HLQ}${PFX}D.DLIB.SMPLOGA:-tseq,-rvb,-l150"
 
 definecsidatasets ${clean} ${datasets}
 if [ $? -gt 0 ]; then
