fixed some more bugs in SMP/E create data definitions work and moved utilities to their own directory

diff --git a/bin/smpcrdddef b/bin/smpcrdddef
--- a/bin/smpcrdddef
+++ b/bin/smpcrdddef
@@ -5,25 +5,24 @@ out=$(whence zbrewfuncs >/dev/null)
 if [ $? -eq 0 ]; then
 	. zbrewfuncs
 else
-	echo "zbrew tools need to be in your PATH"
+	echo "zbrew tools need to be in your PATH" >&2
 	exit 4
 fi
 
 
 #for All but ZFS libraries
 targ_dddefs(){
-libs=`readbom ${ussname} <${smpelibs}`
+libs=`readbom ${zosname} <${smpelibs}`
 rc=$?
 if [ $rc -gt 0 ]; then
-  echo "${libs}"
   exit $rc
 fi
 
-targdddefs=`echo "${libs}" | awk '($7 == "T" && $2 != "ZFS") {print $1}'` 
+targdddefs=`echo "${libs}" | awk '($2 != "ZFS" && $7 == "T") {print $1}'` 
 for targdddef in ${targdddefs}; do
  smpuclin="${smpuclin}
  REP DDDEF(${targdddef})
- DA(${ZBREW_HLQ}${ussname}.${targdddef})
+ DA(${ZBREW_HLQ}${zosname}.${targdddef})
  UNIT(SYSALLDA)
  WAITFORDSN
  SHR.
@@ -31,14 +30,14 @@ for targdddef in ${targdddefs}; do
 done
 
 #for ZFS 
-targdddefs=`echo "${libs}" | awk '($7 == "T" && $2 == "ZFS") {print $1}'`
+targdddefs=`echo "${libs}" | awk '($2 == "ZFS" && $5 == "T") {print $1}'`
 if [ "${dddefpath}" = '0' ]; then
-	dddefpath="${zfsdir}"
+	dddefpath="${ZFSDIR}"
 fi
 for targdddef in ${targdddefs}; do
  smpuclin="${smpuclin}
  REP DDDEF(${targdddef})
- PATH('${zfsroot}${dddefpath}').
+ PATH('${ZFSROOT}${dddefpath}').
 "
 done
 
@@ -57,17 +56,16 @@ done
 }
 
 dist_dddefs(){
-libs=`readbom ${ussname} <${smpelibs}`
+libs=`readbom ${zosname} <${smpelibs}`
 rc=$?
 if [ $rc -gt 0 ]; then
-  echo "${libs}"
   exit $rc
 fi
 distdddefs=`echo "${libs}" | awk '($7 == "D") {print $1}'`
 for distdddef in ${distdddefs};do
  smpuclin="${smpuclin}
  REP DDDEF(${distdddef})
- DA(${ZBREW_HLQ}${ussname}.${distdddef})
+ DA(${ZBREW_HLQ}${zosname}.${distdddef})
  UNIT(SYSALLDA)
  WAITFORDSN
  SHR.
@@ -78,20 +76,23 @@ done
 
 
 run_gimsmp(){
-mvscmdauth --pgm=GIMSMP --smpcsi=${ZBREW_HLQ}${ussname}G.GLOBAL.CSI --sysprint=DUMMY --smprpt=DUMMY --smplist=DUMMY --smpcntl=stdin <<zzz
+mvscmdauth --pgm=GIMSMP --smpcsi=${ZBREW_HLQ}${zosname}G.GLOBAL.CSI --sysprint=DUMMY --smprpt=DUMMY --smplist=DUMMY --smpcntl=stdin <<zzz
 ${smpuclin}
 zzz
         rc=$?
-        if [ $rc -gt 0 ]; then
+        if [ $rc -gt 4 ]; then
+		echo "GIMSMP failed with rc:$rc" >&2
+		echo "${smpuclin}" >&2
                 exit $rc
         fi
+	exit 0
 
 }
 
 
 mydir=$(callerdir ${0})
 prefix=$1
-ussname=$2
+zosname=$2
 shift 2
 opts=$*
 dddefpath=0
@@ -99,15 +100,15 @@ dddefpath=0
 props="${mydir}/../../zbrew/properties/zbrewprops.json"
 zbrewpropse zbrew config "${props}"
 
-props="${mydir}/../../zbrew-${prefix}/${ussname}/${ussname}install.json"
-zbrewpropse "${ussname}" install "${props}"
+props="${mydir}/../../zbrew-${prefix}/${zosname}/${zosname}install.json"
+zbrewpropse "${zosname}" install "${props}"
 
-smpelibs="${mydir}/../../zbrew-${prefix}/${ussname}/${ussname}bom.json"
+smpelibs="${mydir}/../../zbrew-${prefix}/${zosname}/${zosname}bom.json"
 
-ussname=$(echo ${ussname} | tr '[:lower:]' '[:upper:]')
+zosname=$(echo ${zosname} | tr '[:lower:]' '[:upper:]')
 
 # Update Target Zone DDDEFS, note Target Zone contains both Targ/Dist libraries
-smpuclin="  SET   BDY(${ussname}T).
+smpuclin="  SET   BDY(${zosname}T).
      UCLIN.
 "
 targ_dddefs
@@ -120,7 +121,7 @@ run_gimsmp
 
 
 # Update Distribution Zone DDDEFS
-smpuclin="  SET BDY(${ussname}D).
+smpuclin="  SET BDY(${zosname}D).
      UCLIN.
 "
 dist_dddefs
