add in separate REPOROOT

diff --git a/bin/smpfromnts b/bin/smpfromnts
--- a/bin/smpfromnts
+++ b/bin/smpfromnts
@@ -129,13 +129,13 @@ if [ "$prefix" = "ZHW" ]; then
         rm -rf /$ZBREW_TMP/smpnts.ZHW110 2>/dev/null
 	order='order1'
         mkdir -p "${NTS}/${order}"
-        prodpkg="${ZBREW_WORKROOT}/zbrew-${lprefix}/${ussname}/${ussname}crtpkg"
+        prodpkg="${ZBREW_REPOROOT}/zbrew-${lprefix}/${ussname}/${ussname}crtpkg"
         if [ -f "${prodpkg}" ]; then
                 ${prodpkg} ${NTS}/${order}
                 rc=$?
         else
-                echo "Unable to find product packaging program: ${prodpkg}. Installation failed."
-                return 16
+                echo "Unable to find product packaging program: ${prodpkg}. Installation failed." >&2
+                exit 16
         fi
 fi
 
