fix busted build :(

diff --git a/bin/zbrew b/bin/zbrew
--- a/bin/zbrew
+++ b/bin/zbrew
@@ -166,7 +166,7 @@ receive() {
 #
 # Temporary hack - need a better way to locate where pre-req script is
 #
-prereq() {
+prodprereq() {
 	sw=$1
 	shift 1
 	opts=$*
@@ -253,7 +253,7 @@ apply() {
 #
 # Temporary hack - need a better way to locate where installation script is
 #
-install() {
+prodinstall() {
 	sw=$1
 	shift 1
 	opts=$*
@@ -271,6 +271,44 @@ install() {
 		echo "Unable to find product installation program: ${prodinst}. Installation failed."
 		return 16
 	fi
+}
+
+install() {
+	sw=$1
+	shift 1
+	opts=$*
+
+	out=`smpconfig ${sw} ${opts}`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "${out}" >&2
+		return $rc
+	fi
+	out=`receive ${sw} ${opts}`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "${out}" >&2
+		return $rc
+	fi
+	out=`prodprereq ${sw} ${opts}`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "${out}" >&2
+		return $rc
+	fi
+	out=`prodinstall ${sw} ${opts}`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "${out}" >&2
+		return $rc
+	fi
+	out=`apply ${sw} ${opts}`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "${out}" >&2
+		return $rc
+	fi
+	return 0
 }
 
 #
@@ -337,6 +375,14 @@ if [ $? -gt 0 ]; then
 	echo "Internal Error. Unable to find ${props}" >&2
 	exit 4
 fi
+ussname=$(echo ${2} | tr '[:upper:]' '[:lower:]');
+zosname=$(echo ${2} | tr '[:lower:]' '[:upper:]');
+props="${ZBREW_ORDERROOT}/${ussname}.order"
+. zbrewprops "${props}"
+if [ $? -gt 0 ]; then
+        echo "Internal Error. Unable to find ${props}" >&2
+        exit 4
+fi   
 verb=$1
 case ${verb} in
 	search ) 
@@ -350,8 +396,6 @@ case ${verb} in
 		echo "${out}"
 		;;
 	smpconfig )
-		zosname=$(echo ${2} | tr '[:lower:]' '[:upper:]'); 
-        	ussname=$(echo ${2} | tr '[:upper:]' '[:lower:]');
 		if [ ${verbose} -gt 0 ]; then
 			echo "Allocate SMP/E datasets for $2 " >&2
 		fi
@@ -361,8 +405,8 @@ case ${verb} in
 			echo "Unable to configure SMP/E datasets. Receive failed" >&2
 			exit $rc
 		fi
-	receive )
-		zosname=$(echo ${2} | tr '[:lower:]' '[:upper:]'); 
+		;;
+	smpreceive )
 		NTS=`receive ${zosname}`; 
 		rc=$? 
 		if [ $rc -gt 0 ]; then
@@ -372,7 +416,7 @@ case ${verb} in
 			rm -rf ${NTS}
 		fi
 		;;
-	prereq )
+	prodprereq )
 		out=`prereq $2 ${opts}`
 		rc=$? 
 		if [ $rc -gt 0 ]; then
@@ -380,15 +424,15 @@ case ${verb} in
 			exit $rc
 		fi
 		;;
-	install )
-		out=`install $2 ${opts}`;
+	prodinstall )
+		out=`prodinstall $2 ${opts}`;
 		rc=$? 
 		if [ $rc -gt 0 ]; then
 			echo "${out}" 
 			exit $rc
 		fi
 		;;
-	apply )
+	smpapply )
 		out=`apply ${opts} $2`;
 		rc=$? 
 		if [ $rc -gt 0 ]; then
@@ -396,6 +440,14 @@ case ${verb} in
 			exit $rc
 		fi
 		;;	
+	install ) 
+		out=`install $2 ${opts}`;
+		rc=$? 
+		if [ $rc -gt 0 ]; then
+			echo "${out}" 
+			exit $rc
+		fi
+		;;
 	configure ) 
 		out=`configure $2 ${opts}`
 		rc=$?
