had a bug where we need -R to unmount and also to first check the directory exists (since previous -R unmount could delete the directory

diff --git a/bin/zbrew b/bin/zbrew
--- a/bin/zbrew
+++ b/bin/zbrew
@@ -325,20 +325,25 @@ deconfigure() {
 		bom="${ZBREW_WORKROOT}/zbrew-${prefix}/${ussname}/${ussname}bom.json"
 		if ! [ -f "${bom}" ]; then
 			echo "deconfigure: Unable to find BOM file: ${bom}" >&2
+			zbrewlog "deconfigure RC: $?"
 			return $rc
 		fi
 		mountpoints=`readbom "${ussname}" <"${bom}" | awk ' { if ($2 == "ZFS") { print $6; }}'`
 		rc=$?
 		if [ $rc -gt 0 ]; then
 			echo "deconfigure: Unable to read BOM file: ${bom}" >&2
+			zbrewlog "deconfigure RC: $?"
 			return $rc
 		fi
 		for mount in $mountpoints; do
 			absmount="${ZBREW_TGT_ZFSROOT}${mount}"
-			/usr/sbin/unmount "${absmount}"
-			if [ $rc -gt 0 ]; then
-				echo "deconfigure: Unable to unmount ${absmount}" >&2
-				return $rc
+			if [ -d "${absmount}" ]; then
+				/usr/sbin/unmount -R "${absmount}"
+				if [ $rc -gt 0 ]; then
+					echo "deconfigure: Unable to unmount ${absmount}" >&2
+					zbrewlog "deconfigure RC: $?"
+					return $rc
+				fi
 			fi
 		done
 		drm -f "${ZBREW_TGT_HLQ}${zosname}.*"
