increase the size for temporary datasets now that we have to push SMP/E datasets into the archives

diff --git a/bin/zbrewrestore b/bin/zbrewrestore
--- a/bin/zbrewrestore
+++ b/bin/zbrewrestore
@@ -46,13 +46,22 @@ fi
 ussname=$(echo $1 | tr '[:upper:]' '[:lower:]');
 zosname=$(echo $1 | tr '[:lower:]' '[:upper:]');
 prefix=`echo "${ussname}" | awk '{ print substr($1, 0, 3) }'`
+dunzipout="${ZBREW_TMP}/$$dzip.out"
 
-dunzip -s250M "${ZBREW_TMP}/${ussname}.dzp" "${ZBREW_TGT_HLQ%.*}"
+dunzip -s800M "${ZBREW_TMP}/${ussname}.dzp" "${ZBREW_TGT_HLQ%.*}" >${dunzipout} 2>&1
 rc=$?
 if [ $rc -gt 4 ]; then
-	# For now, let a 4 go through because empty datasets cause a 4. Need to see what else can cause a 4
-	echo "zbrewrestore: Restore of archive ${archive} failed." >&2
-	exit $rc
+	# Filter on 'empty dataset' (0ADR744W) message and if that is the only non-informational, treat the unzip as a pass
+	output=`cat "${dunzipout}| | awk '/^0ADR*/ { if (substr($1,8,1) != "I") { if ($1 != "0ADR744W") { print $1; } } }'`
+	if [ "${output}" = "" ]; then
+		rc=0
+		rm -f "${dunzipout}"
+	else
+		echo "zbrewrestore: Restore of archive ${archive} failed." >&2
+		cat "${dunzipout}" >&2
+		rm -f "${dunzipout}"
+		exit $rc
+	fi
 fi
 
 bom="${ZBREW_WORKROOT}/zbrew-${prefix}/${ussname}/${ussname}bom.json"
