add zbrewswinstalled function to make it easy to see if software is installed on the system (true if the variable ZBREW_<sw>HLQ is set to something other than NONE or nothing)

diff --git a/bin/zbrewfuncs b/bin/zbrewfuncs
--- a/bin/zbrewfuncs
+++ b/bin/zbrewfuncs
@@ -7,8 +7,9 @@ callerdir() {
 		fi
 	fi
 	if [ "${calledasdir}" = '' ]; then
-		resolvedas=$(whence "${calledas}")
-		calledasdir="$(dirname ${resolvedas})"
+#		resolvedas=$(whence "${calledas}")
+#		calledasdir="$(dirname ${resolvedas})"
+		calledasdir=$(abspath "${calledas}")
 	fi
 	echo "${calledasdir}"
 }
@@ -129,4 +130,19 @@ zbrewpropse() {
 		exit 4
 	fi
 	return 0
+}
+
+zbrewswinstalled() {
+	sw=$(echo $1 | tr '[:lower:]' '[:upper:]');
+
+	if [ "${sw}" = "" ]; then
+		echo "zbrewswinstalled: Error - need to specify the software to check" >&2
+		return 0
+	fi
+	csi="ZBREW_${sw}HLQ"
+	eval "value=\${$csi}"
+	if [ "${value}" = "" ] || [ "${value}" = "NONE" ]; then
+		return 0
+	fi
+	return 1
 }
