archive and restore into target zip file

diff --git a/bin/zbrew b/bin/zbrew
--- a/bin/zbrew
+++ b/bin/zbrew
@@ -237,6 +237,9 @@ install() {
 			opts="$baseopts -s"
                         runfunc="smpappacc"
                 fi
+                if [ "${runfunc}" = "zbrewarchive" ]; then
+			opts=""
+                fi
 
 		if [ "${restart}" != "NORESTART" ]; then
 			if [ "${zbrewfunc}" != "${restart}" ]; then
@@ -311,6 +314,25 @@ deconfigure() {
 	 	fi
 	fi
 	if [ "${ZBREW_TGT_HLQ}" != "${ZBREW_TGT_HLQ%.*}" ]; then
+		bom="${ZBREW_WORKROOT}/zbrew-${prefix}/${ussname}/${ussname}bom.json"
+		if ! [ -f "${bom}" ]; then
+			echo "deconfigure: Unable to find BOM file: ${bom}" >&2
+			return $rc
+		fi
+		mountpoints=`readbom "${ussname}" <"${bom}" | awk ' { if ($2 == "ZFS") { print $6; }}'`
+		rc=$?
+		if [ $rc -gt 0 ]; then
+			echo "deconfigure: Unable to read BOM file: ${bom}" >&2
+			return $rc
+		fi
+		for mount in $mountpoints; do
+			absmount="${ZBREW_TGT_ZFSROOT}${mount}"
+			/usr/sbin/unmount "${absmount}"
+			if [ $rc -gt 0 ]; then
+				echo "deconfigure: Unable to unmount ${absmount}" >&2
+				return $rc
+			fi
+		done
 		drm -f "${ZBREW_TGT_HLQ}*"
 	fi
 	zbrewlog "deconfigure RC: $?"
diff --git a/bin/zbrewrestore b/bin/zbrewrestore
--- a/bin/zbrewrestore
+++ b/bin/zbrewrestore
@@ -14,6 +14,27 @@ Notes:
      	exit 8
 }
 
+zfsmount() {
+	relzfs="$1"
+	relds="$2"
+	mountpoint="${ZBREW_TGT_ZFSROOT}${relzfs}"
+	
+	mkdir -p -m 755 "${mountpoint}"	
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "zbrewrestore: Error making directory: ${mountpoint}" >&2 
+		return $rc
+	fi
+	/usr/sbin/mount -t zfs -f "${ZBREW_TGT_HLQ}${relds}" "${mountpoint}"
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo "zbrewrestore: Error making directory: ${mountpoint}" >&2 
+		return $rc
+	fi
+	return 0
+}
+
+		
 out=$(whence zbrewfuncs >/dev/null)
 if [ $? -eq 0 ]; then
 	. zbrewfuncs
@@ -21,6 +42,7 @@ else
     	echo "zbrew tools need to be in your PATH" >&2
 	exit 4
 fi
+
 
 mydir=$(callerdir ${0})
 props="${mydir}/../../zbrew/zbrewglobalprops.json"
@@ -35,6 +57,35 @@ fi
 
 ussname=$(echo $1 | tr '[:upper:]' '[:lower:]');
 zosname=$(echo $1 | tr '[:lower:]' '[:upper:]');
+prefix=`echo "${ussname}" | awk '{ print substr($1, 0, 3) }'`
 
 dunzip -s250M "${ZBREW_TMP}/${ussname}.dzp" "${ZBREW_TGT_HLQ%.*}"
+rc=$?
+if [ $rc -gt 0 ]; then
+	echo "zbrewrestore: Restore of archive ${archive} failed." >&2
+	exit $rc
+fi
+
+bom="${ZBREW_WORKROOT}/zbrew-${prefix}/${ussname}/${ussname}bom.json"
+if ! [ -f "${bom}" ]; then
+	echo "zbrewrestore: Unable to find BOM file: ${bom}" >&2
+	exit $rc
+fi
+
+mountpoints=`readbom "${ussname}" <"${bom}" | awk ' { if ($2 == "ZFS") { print $1 ":" $6; }}'`
+rc=$?
+if [ $rc -gt 0 ]; then
+	echo "zbrewrestore: Unable to read BOM file: ${bom}" >&2
+	exit $rc
+fi
+
+for mount in ${mountpoints}; do
+	relds="${zosname}.${mount%%:*}"	
+	relzfs="${mount#*:}"
+	zfsmount "${relzfs}" "${relds}"
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		exit $rc
+	fi
+done
 exit $rc
