adding in smpconfig and smpreceive processing

diff --git a/bin/zoscloud b/bin/zoscloud
--- a/bin/zoscloud
+++ b/bin/zoscloud
@@ -30,18 +30,20 @@ msg() {
 #
 syntax() {
 	echo "\
-zoscloud [-vd] search|install|uninstall|receive|check|configure|apply <software>
+zoscloud [-cvd] search|deploy|remove|receive|check|install|apply|configure <software>
 	and <software> is the software to search for
+	-c: clean files before processing (e.g. delete SMP/E CSI datasets) and clean temporary files after processing (e.g. SMPNTS directory)
 	    
 Examples:
 	zoscloud search cobol      <-- search for products with COBOL in their description
 	zoscloud order igy630j     <-- submit an order for IGY630J software (receive can not be performed until complete)
-	zoscloud install igy630j   <-- install Product 5655-EC6 (Enterprise COBOL 6.3.0) Japanese, ID IGY630J
-	                              (install is short for receive, check, configure, apply)
-	zoscloud receive igy630e   <-- receive COBOL English SMP/E packages from ShopZ
+	zoscloud deploy igy630j    <-- deploy Product 5655-EC6 (Enterprise COBOL 6.3.0) Japanese, ID IGY630J
+	                              (deploy is short for receive, check, install, apply, configure)
+	zoscloud receive igy630e   <-- SMP/E RECEIVE of COBOL English from ShopZ
 	zoscloud check igy630e     <-- check that all pre-reqs required for COBOL English are satisfied
-	zoscloud configure igy630e <-- configure previously checked COBOL English using configuration properties
-	zoscloud apply     igy630e <-- apply previously configured COBOL English, making it available for general use
+	zoscloud install igy630e   <-- run product-specific installation before SMP/E APPLY step
+	zoscloud apply igy630e     <-- SMP/E APPLY of previously installed COBOL English, making it available for general use
+	zoscloud configure igy630e <-- run product-specific configuration after SMP/E APPLY step
 " >&2 
 	exit 16
 }
@@ -57,7 +59,7 @@ search() {
 	return 0
 }
 
-install() {
+deploy() {
 	sw="$1"
 	out=`receive $sw`
 	rc=$?
@@ -71,13 +73,19 @@ install() {
 		echo ${out}
 		return ${rc}
 	fi
-	out=`configure $sw`
+	out=`install $sw`
 	rc=$?
 	if [ $rc -gt 0 ]; then
 		echo ${out}
 		return ${rc}
 	fi
 	out=`apply $sw`
+	rc=$?
+	if [ $rc -gt 0 ]; then
+		echo ${out}
+		return ${rc}
+	fi
+	out=`configure $sw`
 	rc=$?
 	if [ $rc -gt 0 ]; then
 		echo ${out}
@@ -96,14 +104,13 @@ order() {
 	return 0
 }
 
-uninstall() {
+remove() {
 	echo "Not implemented yet"
 	return 4
 }
 
 receive() {
-
-	sw="$1"
+	zosname="$1"
 	tmpServerHFS=${TMP}/server.$$.xml
 	tmpClientHFS=${TMP}/client.$$.xml
 	tmpCntlHFS=${TMP}/cntl.$$.xml
@@ -151,17 +158,22 @@ zzz
 	RPT=${TMP}/$$.smprpt
 	touch ${RPT}
 
-	NTS=${TMP}/$$.smpnts
-	rm -rf ${NTS}
-	mkdir ${NTS}
+	BPXPRINT=${TMP}/$$.bpxprint
+	touch ${BPXPRINT}
 
-	mvscmdauth --pgm=gimsmp --smpcsi=${SMPE_CSI} --smpwkdir=${TMP} --smpnts=${NTS} --smplog=${LOG},mod --smpout=${OUT},mod --smprpt=${RPT},mod --server=${tmpServerHFS} --client=${tmpClientHFS} --smpcntl=${tmpCntlHFS} --bpxprint='*' --sysprint='*' 
+	SYSPRINT=${TMP}/$$.sysprint
+	touch ${SYSPRINT}
+
+	NTS=${TMP}/smpnts
+	mkdir -p ${NTS}
+
+	mvscmdauth --pgm=gimsmp --smpcsi=${zosname}G.GLOBAL.CSI --smpwkdir=${TMP} --smpnts=${NTS} --smplog=${LOG},mod --smpout=${OUT},mod --smprpt=${RPT},mod --bpxprint=${BPXPRINT},mod --sysprint=${SYSPRINT},mod --server=${tmpServerHFS} --client=${tmpClientHFS} --smpcntl=${tmpCntlHFS}
 	rc=$?
 	if [ ${rc} -gt 0 ]; then
-		echo "SMP/E RECEIVE of ${sw} failed. See SMPLOG: ${LOG}, SMPOUT: ${OUT}, SMPRPT: ${RPT} for details."
+		echo "SMP/E RECEIVE of ${sw} failed. See SYSPRINT: ${SYSPRINT}, BPXPRINT: ${BPXPRINT}, SMPLOG: ${LOG}, SMPOUT: ${OUT}, SMPRPT: ${RPT} for details."
 		echo "SMP/E RECEIVE INPUT Files have been retained: server:${tmpServerHFS} client:${tmpClientHFS} smpcntl:${tmpCntlHFS}"
 	else
-		rm -rf ${NTS} ${LOG} ${OUT} ${RPT} 
+		rm -rf ${LOG} ${OUT} ${RPT} ${BPXPRINT} ${SYSPRINT}
 		rm ${tmpOrderHFS} ${tmpClientHFS} ${tmpCntlHFS}
 	fi
 
@@ -172,7 +184,7 @@ check() {
 	return 0
 }
 
-configure() {
+install() {
 	return 0
 }
 
@@ -180,16 +192,27 @@ apply() {
 	return 0
 }
 
+configure() {
+	return 0
+}
+
 debug=0
 verbose=0
-while getopts ":vd" opt; do
+clean=0
+opts=""
+while getopts ":cvd" opt; do
   case ${opt} in
     d )
       debug=1
+      opts="${opts} -d"
+      ;;
+    c )
+      clean=1
+      opts="${opts} -c"
       ;;
     v )
       verbose=1
-      opts="-v"
+      opts="${opts} -v"
       ;;
     \?)
       if [ ${OPTARG} != "?" ]; then
@@ -221,22 +244,29 @@ case ${verb} in
 		rc=$?  
 		echo "${out}"
 		;;
-	install ) 
-		out=`install $2`
+	deploy ) 
+		out=`deploy $2`
 		rc=$?
 		;;
-	uninstall ) 
-		out=`uninstall $2`
+	remove ) 
+		out=`remove $2`
 		rc=$?
 		;;	
-	receive ) 
-		props="${SMPE_ORDERROOT}/$2.properties"
+	receive )
+		ussname=$(echo ${2} | tr '[:upper:]' '[:lower:]'); 
+		zosname=$(echo ${2} | tr '[:lower:]' '[:upper:]'); 
+		props="${SMPE_ORDERROOT}/${ussname}.properties"
 		. zoscloudprops "${props}"
 		if [ $? -gt 0 ]; then
 			echo "ORDER for $2 is not ready yet (unable to find ${props})" >&2
 			exit 4
 		fi
-		out=`receive $2`; 
+		smpconfig ${opts} ${zosname}
+		if [ $? -gt 0 ]; then
+			echo "Unable to configure SMP/E datasets. Receive failed" >&2
+			exit 4
+		fi
+		out=`receive ${zosname}`; 
 		rc=$? 
 		if [ $rc -gt 0 ]; then
 			echo "${out}" 
@@ -246,12 +276,16 @@ case ${verb} in
 		out=`check $2`
 		rc=$?
 		;;	
-	configure ) 
-		out=`configure $2`
-		rc=$?
-		;;	
+	install ) 
+		out=`install $2`;
+		rc=$?;
+		;;
 	apply ) 
 		out=`apply $2`
+		rc=$?
+		;;	
+	configure ) 
+		out=`configure $2`
 		rc=$?
 		;;	
 	* ) msg zoscloud ${UnknownAction} E ${verb}; exit 16;;
